// BeholdService.idl : IDL source for BeholdService.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (BeholdService.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(A3CABF23-7E52-4995-9927-605B1E8DB0E5),
		dual,
		helpstring("IBeholderRC Interface"),
		pointer_default(unique)
	]
	interface IBeholderRC : IDispatch
	{
		[propget, id(1), helpstring("property Name")] HRESULT Name([in] ULONG index, [out, retval] BSTR *pVal);
		[propget, id(2), helpstring("property Count")] HRESULT Count([out, retval] ULONG* count);
		[id(3), helpstring("method Run")] HRESULT Run([in] BSTR* bcstr, [out, retval] VARIANT_BOOL *succes);
		[id(4), helpstring("method SelectCard")] HRESULT SelectCard([in] ULONG* index, [out, retval] VARIANT_BOOL* succes);
		[id(5), helpstring("method GetRemote")] HRESULT GetRemote([out, retval] ULONG* code);
		[id(6), helpstring("method GetRemoteEx")] HRESULT GetRemoteEx([out, retval] ULONG* code);
	};

[
	uuid(BADE98B6-B459-41F5-B998-4DB8A6D05C34),
	version(1.0),
	helpstring("BeholdService 1.0 Type Library")
]
library BEHOLDSERVICELib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(BF7C066C-904C-447E-A457-48B43F9D7959),
		helpstring("BeholderRC Class")
	]
	coclass BeholderRC
	{
		[default] interface IBeholderRC;
	};
};
