// BeholdService.idl : IDL source for BeholdService.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (BeholdService.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(274A76A7-C5D9-4BE8-9327-6D56F25D5AAB),
		dual,
		helpstring("IBeholderRC Interface"),
		pointer_default(unique)
	]
	interface IBeholderRC : IDispatch
	{
		[propget, id(1), helpstring("property Count")] HRESULT Count([out, retval] ULONG *pVal);
		[propget, id(2), helpstring("property IsInit")] HRESULT IsInit([out, retval] VARIANT_BOOL *pVal);
		[propget, id(3), helpstring("property Name")] HRESULT Name([in] ULONG index, [out, retval] BSTR *pVal);
		[id(4), helpstring("method GetRemote")] HRESULT GetRemote([out, retval] ULONG* code);
		[id(5), helpstring("method GetRemoteEx")] HRESULT GetRemoteEx([out, retval] ULONG* code);
		[id(6), helpstring("method Run")] HRESULT Run([in] BSTR* bcstr, [out, retval] VARIANT_BOOL *succes);
		[id(7), helpstring("method SelectCard")] HRESULT SelectCard([in] ULONG index, [out, retval] VARIANT_BOOL* succes);
	};

[
	uuid(A20C10C0-C90E-4998-B3EA-D2BCD7FF409D),
	version(1.0),
	helpstring("BeholdService 1.0 Type Library")
]
library BEHOLDSERVICELib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(1929458C-10F9-4E69-9679-6F9E1273ABE5),
		helpstring("BeholderRC Class")
	]
	coclass BeholderRC
	{
		[default] interface IBeholderRC;
	};
};
